### ISSUE TITLE
Is fp16 supported under multi-gpu ？I see that mixed_precision related code is commented in custom_optimization.py. 

### ISSUE THREAD

**Issue by wrxDM** [HaoyuHu/bert-multi-gpu#18]

**Comment by wrxDM** [comment]
when i uncomment mixed_precision related code in custom_optimization.py, i get ValueError: Outputs of true_fn and false_fn must have the same type: int64, bool ..

**Comment by haoyuhu** [comment]
This project does not support using FP16 under Multi-GPU mode, because `LossScaleOptimizer` haven't been updated for `DistributionStrategy`. And I can't solve this compatibility problem at the moment, even if I hacked the code. 
If you solve this problem, pull requests are welcome. Thanks!
REF: https://github.com/tensorflow/tensorflow/issues/25080
